//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Up
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_Staff { get; set; }
        public string StaffSurname { get; set; }
        public string StaffName { get; set; }
        public string StaffMiddleName { get; set; }
        public string StaffContact { get; set; }
        public int Position_ID { get; set; }
        public Nullable<int> Store_ID { get; set; }
    
        public virtual Positions Positions { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
