//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Up
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresSupplier
    {
        public int ID_StoresSupplier { get; set; }
        public int Store_ID { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Stores Stores { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
